language: java
jdk:
- oraclejdk8

sudo: false

services:
  - redis-server

before_install:
  - cd API
  - chmod +x mvnw

install: 
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script: mvn clean install

notifications:
  email:
    recipients:
      - devnicolasmozo@gmail.com
    on_success: [always|never|change] # default: change
 