language: java
sudo: false
services:
  - redis-server
before_install: cd API
install: mvn clean install
notifications:
  email:
    recipients:
      - devnicolasmozo@gmail.com
    on_success: [always|never|change] # default: change
 