language: java
sudo: false
before_install: cd API
script: mvn clean test
notifications:
  email:
    recipients:
      - devnicolasmozo@gmail.com
    on_success: [always|never|change] # default: change
 